= Patternbot Documentation
:toc:
:experimental:
:source-highlighter: rouge

== All you need is a folder

[.folder-tree]
. icon:folder[size=16] my-pattern-lib
.. icon:file-empty[size=16] (_empty_)

'''

== Viewing the pattern library

btn:[Browse patterns]

kbd:[⌘B]

menu:File[Browse Pattern Library]

'''

== Main readme
=== Define the pattern library’s name
=== Describe the pattern library

'''

== The commmon folder
=== Web Dev tools

* Gridifier
* Modulifier
* Typografier

=== Configure colours
==== Describe the colours
=== Configure typefaces
==== Define font URLs
==== Describe the typefaces

'''

== Configure the pattern library
=== Change the background colour
=== Adjust the accent colour

'''

== The patterns folder
=== Add a pattern
=== Multi-file patterns
=== Using CSS with patterns
==== The common CSS
=== Describe patterns with a readme
==== Describe multiple pattern HTML files
==== Set the display background colour
==== Set a default display width
==== Set a default display height
==== Set a default display padding

'''

== The images folder
=== Displaying different logo sizes
=== Showing the icon sprite sheet

'''

== Set a display background colour for built-in patterns

'''

== Main readme quick reference

[source,markdown]
----
---
name: "Pattern Library Name" <1>

background-color: "--color-accent-grey" <3>
accent-color: "--color-primary" <4>

font-url: "https://fonts.googleapis.com/css?family=Roboto:400,400i,700" <5>
output-file: "pattern-library.html" <6>

fonts: <7>
  primary: | <8>
    This is a description. <9>
  secondary: |
    This is a description.
  accent: |
    This is a description.

colours: <10>
  primary: | <11>
    This is a description.
  secondary: |
    This is a description.
  accent: |
    This is a description.
  neutral: |
    This is a description.

brand: <12>
  logos: <13>
    background-color: "#e2e2e2" <14>
  colours:
    background-color: "--color-accent-not-as-bright"
  typefaces:
    background-color: "magenta"

icons:
  icons:
    background-color: "--color-accent" <15>
    icon-id-1: <16>
      background-color: "--color-neutral" <17>
---

The main description for the pattern library goes here. <2>
----
[.code-labels]
<1> The name of the pattern library, shown in the navigation & brand section
<2> The pattern library description, shown at the top, in the brand section, next to the logos
<3> Set the background colour of the whole pattern library: use theme variables, hex colours, or CSS colour names
<4> Set the accent colour, used on important headings; _default:_ the primary colour

'''

== Pattern readme quick reference

[source,markdown]
----
---
image-card: | <2>
  The description for the image card. <3>

link-card: <4>
  width: 400 <5>
  height: 600 <6>
  padding: "1em" <7>
  background-color: "--var-neutral-dark" <8>
  description: | <9>
    This is the description here.

icon-card:
  hideCode: true <10>
  notResizable: true <11>
  hidePopOutButton: true <12>
---

Describe all the patterns together as a group. <1>
----

=== Pattern readme simple version

[source,markdown]
----
Description for a pattern that includes one a single HTML file.
----
